project:
  type: website

website:
  title: "Fonctions et programmation fonctionnelle"
  sidebar:
    style: "floating"
    contents:
      - href: index.qmd
        text: Introduction
      - href: fonctions.qmd
        text: Rappel sur les fonctions en R
    search: false

format:
  html:
    toc: true

filters:
  - webr
  - naquiz

webr: 
  show-startup-message: false
