project:
  type: website

website:
  title: "Fonctions et programmation fonctionnelle"
  sidebar:
    style: "floating"
    contents:
      - href: index.qmd
        text: Paradigmes de programmation
      - href: programmation_objet.qmd
        text: Programmation objet
    search: false

format:
  html:
    toc: true

filters:
  - webr
  - naquiz

webr: 
  show-startup-message: false